name: anglican_hymn_sync
description: "A modern Anglican Hymnal App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  google_fonts: ^6.1.0
  wakelock_plus: ^1.1.4
  mobile_scanner: ^6.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#0B132B"
    theme_color: "#0B132B"

flutter:
  uses-material-design: true
  assets:
    - assets/hymns-full.json
    - assets/audio-catalogue.json
    - assets/images/app_icon.png
