const axios = require('axios');
const cheerio = require('cheerio');
const fs = require('fs');

const BASE = "https://aznimi.com/luganda/enjatula-luganda-anglican-hymns-song-lyrics";

// Array of hymn slugs
const HYMN_SLUGS = [
  { n: 1, slug: "oluyimba-1-tuzuukuketuzuukuke-song-lyrics" },
  { n: 2, slug: "oluyimba-2-yesu-mukama-weggulu-song-lyrics" },
  { n: 3, slug: "oluyimba-3-bwe-bukedde-olwa-leero-song-lyrics" },
  { n: 4, slug: "oluyimba-4-mukama-waffe-bulijjo-song-lyrics" },
  { n: 5, slug: "oluyimba-5-jjangu-gye-ndi-bwe-nzuukuka-song-lyrics" },
  { n: 6, slug: "oluyimba-6-enkya-bwonoozuukukanga-song-lyrics" },
  { n: 7, slug: "oluyimba-7-zuukuka-ggwe-omwoyo-gwange-song-lyrics" },
  { n: 8, slug: "oluyimba-8-ggwe-musana-gwobulamu-song-lyrics" },
  { n: 9, slug: "oluyimba-9-gyoli-yesu-tuwaayo-song-lyrics" },
  { n: 10, slug: "oluyimba-10-ompulire-kitaffe-song-lyrics" },
  { n: 11, slug: "oluyimba-11-kabaka-wange-song-lyrics" },
  { n: 12, slug: "oluyimba-12-enjuba-yomwoyo-gwange-song-lyrics" },
  { n: 13, slug: "oluyimba-13-musana-mulungi-song-lyrics" },
  { n: 14, slug: "oluyimba-14-kaakano-buli-kintu-song-lyrics" },
  { n: 15, slug: "oluyimba-15-obudde-buzibye-song-lyrics" },
  { n: 16, slug: "oluyimba-16-guweddewo-omusana-song-lyrics" },
  { n: 17, slug: "oluyimba-17-nga-tebunnaba-kuziba-song-lyrics" },
  { n: 18, slug: "oluyimba-18-beera-nangeobudde-buzibye-song-lyrics" },
  { n: 19, slug: "oluyimba-19-mulokozi-waffe-gwe-twagala-song-lyrics" },
  { n: 20, slug: "oluyimba-20-olunaku-lwafe-luno-song-lyrics" },
  { n: 21, slug: "oluyimba-21-ayi-musumba-omuteefu-song-lyrics" },
  { n: 22, slug: "oluyimba-22-ayi-kitaffe-omutonzi-song-lyrics" },
  { n: 23, slug: "oluyimba-23-katonda-wange-nkwebaza-song-lyrics" },
  { n: 24, slug: "oluyimba-24-omukisa-gwa-kitaffe-song-lyrics" },
  { n: 25, slug: "oluyimba-25-kitaffe-twewaayo-song-lyrics" },
  { n: 26, slug: "oluyimba-26-jjangu-ggwe-omununuzi-waffe-song-lyrics" },
  { n: 27, slug: "oluyimba-27-muzuukuke-mmwe-abeebase-song-lyrics" },
  { n: 28, slug: "oluyimba-28-yesu-alijja-nebire-song-lyrics" },
  { n: 29, slug: "oluyimba-29-musanyuke-abalokole-song-lyrics" },
  { n: 30, slug: "oluyimba-30-ekiro-kiyise-song-lyrics" },
  { n: 31, slug: "oluyimba-31-yesu-omulindwa-jjangu-song-lyrics" },
  { n: 32, slug: "oluyimba-32-mulokozi-waffe-yatugamba-song-lyrics" },
  { n: 33, slug: "oluyimba-33-labaanaawasa-omugole-ekiro-ajja-song-lyrics" },
  { n: 34, slug: "oluyimba-34-mmwe-mwenna-abalonde-song-lyrics" },
  { n: 35, slug: "oluyimba-35-abakristaayo-boona-abomu-nsi-song-lyrics" },
  { n: 36, slug: "oluyimba-36-obudde-bwali-bwa-ttumbi-song-lyrics" },
  { n: 37, slug: "oluyimba-37-omwami-wekitiibwa-kyonna-bwe-yajja-ku-nsi-song-lyrics" },
  { n: 38, slug: "oluyimba-38-abasumba-baali-bakuuma-song-lyrics" },
  { n: 39, slug: "oluyimba-39-mu-kujaguza-okungi-song-lyrics" },
  { n: 40, slug: "oluyimba-40-mu-kibuga-kya-dawudi-song-lyrics" },
  { n: 41, slug: "oluyimba-41-omwana-yazaalibwa-song-lyrics" },
  { n: 42, slug: "oluyimba-42-leero-bamalayika-song-lyrics" },
  { n: 43, slug: "oluyimba-43-mu-biro-ebyempewo-song-lyrics" },
  { n: 44, slug: "oluyimba-44-owange-munnange-jjukirajjukira-song-lyrics" },
  { n: 45, slug: "oluyimba-45-baani-abayimba-tobawulira-song-lyrics" },
  { n: 46, slug: "oluyimba-46-ekiro-kya-ssekukkulu-song-lyrics" },
  { n: 47, slug: "oluyimba-47-kino-kya-ktalo-nnyo-song-lyrics" },
  { n: 48, slug: "oluyimba-48-ye-kigambo-wa-katonda-song-lyrics" },
  { n: 49, slug: "oluyimba-49-ku-lunaku-luno-song-lyrics" },
  { n: 50, slug: "oluyimba-50-laba-omwana-mu-kiraalo-omu-song-lyrics" },
  { n: 51, slug: "oluyimba-51-ggwe-kibuga-beesirekemu-song-lyrics" },
  { n: 52, slug: "oluyimba-52-mu-kisibo-kyente-e-beesirekemu-song-lyrics" },
  { n: 53, slug: "oluyimba-53-yesu-omwana-owekisa-song-lyrics" },
  { n: 54, slug: "oluyimba-54-nsanyukira-oluyimba-song-lyrics" },
  { n: 55, slug: "oluyimba-55-laba-omwana-azaalidwa-song-lyrics" },
  { n: 56, slug: "oluyimba-56-ekiseera-kye-kituuse-song-lyrics" },
  { n: 57, slug: "oluyimba-57-omwana-e-beesirekemu-song-lyrics" },
  { n: 58, slug: "oluyimba-58-essanyu-lingi-mu-ggulu-song-lyrics" },
  { n: 59, slug: "oluyimba-59-eggye-lyonna-eryomu-ggulu-song-lyrics" },
  { n: 60, slug: "oluyimba-60-yesu-nga-bwe-yazaalibwa-song-lyrics" },
  { n: 61, slug: "oluyimba-61-ayi-kitangenkwesiga-song-lyrics" },
  { n: 62, slug: "oluyimba-62-tweyanziza-ekisa-kyo-song-lyrics" },
  { n: 63, slug: "oluyimba-63-abagezigezi-edda-song-lyrics" },
  { n: 64, slug: "oluyimba-64-mmunyeenye-eyakira-bonna-song-lyrics" },
  { n: 65, slug: "oluyimba-65-otubeere-mmunyeenye-ennungi-song-lyrics" },
  { n: 66, slug: "oluyimba-66-laba-emmunyeenye-ennungi-ennyo-song-lyrics" },
  { n: 67, slug: "oluyimba-67-abantu-abaabeeranga-song-lyrics" },
  { n: 68, slug: "oluyimba-68-yesu-mukama-waffe-song-lyrics" },
  { n: 69, slug: "oluyimba-69-katonda-bwe-baalumwa-ennyo-song-lyrics" },
  { n: 70, slug: "oluyimba-70-yesu-ffe-mu-maaso-go-song-lyrics" },
  { n: 71, slug: "oluyimba-71-binkooyesa-ebibi-byange-song-lyrics" },
  { n: 72, slug: "oluyimba-72-tuli-boonoonyi-ddala-song-lyrics" },
  { n: 73, slug: "oluyimba-73-mu-kwetaaga-kwaffe-okungi-song-lyrics" },
  { n: 74, slug: "oluyimba-74-ebyonoono-byange-binkooyesa-song-lyrics" },
  { n: 75, slug: "oluyimba-75-tusaasire-ffe-abanaku-song-lyrics" },
  { n: 76, slug: "oluyimba-76-oweebwe-nnyo-ekitibwa-song-lyrics" },
  { n: 77, slug: "oluyimba-77-bwe-ndowooza-omusaalaba-song-lyrics" },
  { n: 78, slug: "oluyimba-78-ggwe-yerusaalemi-song-lyrics" },
  { n: 79, slug: "oluyimba-79-omutwe-gwa-mukama-song-lyrics" },
  { n: 80, slug: "oluyimba-80-okwagala-okwo-song-lyrics" },
  { n: 81, slug: "oluyimba-81-ewala-mu-buyudaaya-song-lyrics" },
  { n: 82, slug: "oluyimba-82-ekibi-kiruwa-kye-wali-okoze-song-lyrics" },
  { n: 83, slug: "oluyimba-83-yesu-azuukidde-olwa-leero-aleruuya-song-lyrics" },
  { n: 84, slug: "oluyimba-84-yesu-waali-okufa-song-lyrics" },
  { n: 85, slug: "oluyimba-85-yesu-eyali-mu-nvuba-song-lyrics" },
  { n: 86, slug: "oluyimba-86-aleruuya-aleruuya-aleeruya-song-lyrics" },
  { n: 87, slug: "oluyimba-87-ku-lunaku-olukulu-song-lyrics" },
  { n: 88, slug: "oluyimba-88-leero-lwa-ssanyu-nnyo-song-lyrics" },
  { n: 89, slug: "oluyimba-89-aleruuya-aleruuya-aleruuya-song-lyrics" },
  { n: 90, slug: "oluyimba-90-yasula-mu-ntaana-mukama-waffe-song-lyrics" },
  { n: 91, slug: "oluyimba-91-aleruuya-aleruuya-song-lyrics" },
  { n: 92, slug: "oluyimba-92-yesu-omulokozi-song-lyrics" },
  { n: 93, slug: "oluyimba-93-kabaka-mukama-waffe-song-lyrics" },
  { n: 94, slug: "oluyimba-94-aleruuya-myimbe-song-lyrics" },
  { n: 95, slug: "oluyimba-95-leero-azuukidde-song-lyrics" },
  { n: 96, slug: "oluyimba-96-olunaku-nga-lukulu-aleruuya-song-lyrics" },
  { n: 97, slug: "oluyimba-97-tusinza-nnyo-erinnya-lyo-song-lyrics" },
  { n: 98, slug: "oluyimba-98-ayi-yesu-ggwe-atudde-song-lyrics" },
  { n: 99, slug: "oluyimba-99-mumusseeko-engule-song-lyrics" },
  { n: 100, slug: "oluyimba-100-mumuyimbire-mukama-song-lyrics" },
  { n: 101, slug: "oluyimba-101-yesu-ngaddayo-gye-yava-song-lyrics" },
  { n: 102, slug: "oluyimba-102-omwoyo-omutukuvu-jjangu-song-lyrics" },
  { n: 103, slug: "oluyimba-103-edda-katonda-bwe-yakka-song-lyrics" },
  { n: 104, slug: "oluyimba-104-jjangu-mwoyo-wa-yesu-song-lyrics" },
  { n: 105, slug: "oluyimba-105-omwoyo-omutukuvu-song-lyrics" },
  { n: 106, slug: "oluyimba-106-olwa-leero-mbagaolunaku-luno-lukulu-song-lyrics" },
  { n: 107, slug: "oluyimba-107-abatukuvu-ba-katonda-song-lyrics" },
  { n: 108, slug: "oluyimba-108-abalokole-ba-yesube-yatuusa-mu-ggulu-song-lyrics" },
  { n: 109, slug: "oluyimba-109-katonda-yagaba-eggye-song-lyrics" },
  { n: 110, slug: "oluyimba-110-erinnya-lyo-yesu-lyebazibwe-song-lyrics" },
  { n: 111, slug: "oluyimba-111-ka-tutambulenga-nabo-song-lyrics" },
  { n: 112, slug: "oluyimba-112-ayi-kitaffe-atwagala-song-lyrics" },
  { n: 113, slug: "oluyimba-113-mu-mikonogyo-yesu-song-lyrics" },
  { n: 114, slug: "oluyimba-114-omulokozi-yesu-song-lyrics" },
  { n: 115, slug: "oluyimba-115-omusumba-omulungi-song-lyrics" },
  { n: 116, slug: "oluyimba-116-yesu-naawe-wali-song-lyrics" },
  { n: 117, slug: "oluyimba-117-tusanyuse-okujja-mu-maaso-go-song-lyrics" },
  { n: 118, slug: "oluyimba-118-twala-obulamu-bwange-song-lyrics" },
  { n: 119, slug: "oluyimba-119-twateekebwako-omusaalaba-song-lyrics" },
  { n: 120, slug: "oluyimba-120-katonda-wange-nkuwadde-song-lyrics" },
  { n: 121, slug: "oluyimba-121-alijjaessubi-eryo-song-lyrics" },
  { n: 122, slug: "oluyimba-122-enjala-nennyonta-song-lyrics" },
  { n: 123, slug: "oluyimba-123-mujje-muweebwe-ekijukizo-song-lyrics" },
  { n: 124, slug: "oluyimba-124-kabaka-owekisatunuulira-song-lyrics" },
  { n: 125, slug: "oluyimba-125-yesu-omubiri-gwo-yemmere-song-lyrics" },
  { n: 126, slug: "oluyimba-126-laba-emmeza-yange-song-lyrics" },
  { n: 127, slug: "oluyimba-127-ggwe-omwoyo-gwangeweeyonje-song-lyrics" },
  { n: 128, slug: "oluyimba-128-ggwe-emmere-yobugenyi-song-lyrics" },
  { n: 129, slug: "oluyimba-129-kristobwatyobwe-yeewayo-song-lyrics" },
  { n: 130, slug: "oluyimba-130-yesu-wakati-mu-ffe-song-lyrics" },
  { n: 131, slug: "oluyimba-131-ggwe-akamwa-kange-tendanga-song-lyrics" },
  { n: 132, slug: "oluyimba-132-ekitiibwa-kibe-waggulu-song-lyrics" },
  { n: 133, slug: "oluyimba-133-nyweza-ayi-katonda-emikono-song-lyrics" },
  { n: 134, slug: "oluyimba-134-mujje-nga-mwetereereka-song-lyrics" },
  { n: 135, slug: "oluyimba-135-tuzze-gyoliayi-katonda-song-lyrics" },
  { n: 136, slug: "oluyimba-136-ayi-ggwe-kwagalaggwe-asinga-byonna-song-lyrics" },
  { n: 137, slug: "oluyimba-137-abantu-bonna-abensi-song-lyrics" },
  { n: 138, slug: "oluyimba-138-ayi-katonda-bwe-ndowooza-song-lyrics" },
  { n: 139, slug: "oluyimba-139-bamalayika-bayimba-song-lyrics" },
  { n: 140, slug: "oluyimba-140-ebintu-ebirungi-nebintu-ebikulu-song-lyrics" },
  { n: 141, slug: "oluyimba-141-eggulu-likusinza-song-lyrics" },
  { n: 142, slug: "oluyimba-142-enkya-bwe-nzuukuka-song-lyrics" },
  { n: 143, slug: "oluyimba-143-ensi-zoonawe-zifa-zenkana-song-lyrics" },
  { n: 144, slug: "oluyimba-144-ggwe-katonda-ataggwaawo-song-lyrics" },
  { n: 145, slug: "oluyimba-145-ggwe-wekka-ataggwaawoowamagezi-song-lyrics" },
  { n: 146, slug: "oluyimba-146-ka-tumusinzekatonda-waffe-song-lyrics" },
  { n: 147, slug: "oluyimba-147-mukama-omuyinza-wa-byonnaomutonzi-song-lyrics" },
  { n: 148, slug: "oluyimba-148-mumutende-ye-song-lyrics" },
  { n: 149, slug: "oluyimba-149-okwolesebwa-kulungi-song-lyrics" },
  { n: 150, slug: "oluyimba-150-tukweyanza-kitaffe-song-lyrics" },
  { n: 151, slug: "oluyimba-151-tumuyimbire-mukama-song-lyrics" },
  { n: 152, slug: "oluyimba-152-weebaze-ggwe-emmeeme-yange-song-lyrics" },
  { n: 153, slug: "oluyimba-153-aleruuya-mumwebaze-song-lyrics" },
  { n: 154, slug: "oluyimba-154-essanyu-eringi-eritakomezeka-song-lyrics" },
  { n: 155, slug: "oluyimba-155-yesutotegeerekeka-song-lyrics" },
  { n: 156, slug: "oluyimba-156-ewala-mu-ggulu-song-lyrics" },
  { n: 157, slug: "oluyimba-157-mujje-mwebaze-mukama-song-lyrics" },
  { n: 158, slug: "oluyimba-158-mukama-waffe-owobulamu-song-lyrics" },
  { n: 159, slug: "oluyimba-159-mu-maaso-ga-yesu-abalokole-song-lyrics" },
  { n: 160, slug: "oluyimba-160-yesu-ye-yava-mu-ggulu-song-lyrics" },
  { n: 161, slug: "oluyimba-161-laba-omwana-omuto-song-lyrics" },
  { n: 162, slug: "oluyimba-162-ggwe-eyaleka-ekitiibwa-kyo-song-lyrics" },
  { n: 163, slug: "oluyimba-163-tetwakulaba-bwe-wajja-song-lyrics" },
  { n: 164, slug: "oluyimba-164-mujaguze-nno-song-lyrics" },
  { n: 165, slug: "oluyimba-165-erinnya-lya-yesu-ddungi-song-lyrics" },
  { n: 166, slug: "oluyimba-166-tulina-omubeezi-waffe-song-lyrics" },
  { n: 167, slug: "oluyimba-167-yesuggwe-eyanjagala-song-lyrics" },
  { n: 168, slug: "oluyimba-168-yesu-alifuga-wonna-song-lyrics" },
  { n: 169, slug: "oluyimba-169-neegomba-nnyo-okuwulira-song-lyrics" },
  { n: 170, slug: "oluyimba-170-mukama-waffe-mulokozi-song-lyrics" },
  { n: 171, slug: "oluyimba-171-omusumba-wange-mukama-song-lyrics" },
  { n: 172, slug: "oluyimba-172-okwagala-okutaggwaawo-song-lyrics" },
  { n: 173, slug: "oluyimba-173-omuzira-waffeomwana-womuntu-song-lyrics" },
  { n: 174, slug: "oluyimba-174-yesu-ggwe-oli-ssanyu-lyaffe-song-lyrics" },
  { n: 175, slug: "oluyimba-175-yesussanyu-lyange-song-lyrics" },
  { n: 176, slug: "oluyimba-176-olwazi-lwedda-nedda-gwe-song-lyrics" },
  { n: 177, slug: "oluyimba-177-yesu-mulokozi-wange-song-lyrics" },
  { n: 178, slug: "oluyimba-178-nnaateekanga-ku-yesu-omwana-gwendiga-song-lyrics" },
  { n: 179, slug: "oluyimba-179-ennaku-bwe-zifumita-song-lyrics" },
  { n: 180, slug: "oluyimba-180-yesu-eyakubibwa-edda-song-lyrics" },
  { n: 181, slug: "oluyimba-181-ggwe-eyatonda-olwa-okwagala-kwo-song-lyrics" },
  { n: 182, slug: "oluyimba-182-yesumwana-womuntu-song-lyrics" },
  { n: 183, slug: "oluyimba-183-yesu-obuyinike-bwaffe-song-lyrics" },
  { n: 184, slug: "oluyimba-184-yesu-omulokozi-song-lyrics" },
  { n: 185, slug: "oluyimba-185-ettendo-lingi-mu-ggulu-song-lyrics" },
  { n: 186, slug: "oluyimba-186-omusaayi-ogwensolo-song-lyrics" },
  { n: 187, slug: "oluyimba-187-mumutende-yesu-omununuzi-waffe-song-lyrics" },
  { n: 188, slug: "oluyimba-188-bwalijja-mukama-waffe-song-lyrics" },
  { n: 189, slug: "oluyimba-189-omukulu-wekkanisa-song-lyrics" },
  { n: 190, slug: "oluyimba-190-katonda-eyannonda-nze-song-lyrics" },
  { n: 191, slug: "oluyimba-191-mwenna-musanyuke-song-lyrics" },
  { n: 192, slug: "oluyimba-192-ggwe-ekkubo-lyaffe-era-mu-ggwe-song-lyrics" },
  { n: 193, slug: "oluyimba-193-mugabi-webirabo-ebirungi-song-lyrics" },
  { n: 194, slug: "oluyimba-194-yesu-ekisa-kyo-ekingi-song-lyrics" },
  { n: 195, slug: "oluyimba-195-omwoyo-omutukuvu-song-lyrics" },
  { n: 196, slug: "oluyimba-196-kabaka-weggulu-song-lyrics" },
  { n: 197, slug: "oluyimba-197-ggwe-oli-mutukuvumukama-katonda-song-lyrics" },
  { n: 198, slug: "oluyimba-198-ka-tusuute-kitaffe-song-lyrics" },
  { n: 199, slug: "oluyimba-199-tukwebaza-kitaffe-song-lyrics" },
  { n: 200, slug: "oluyimba-200-nze-nzikiriza-ddala-song-lyrics" },
  { n: 201, slug: "oluyimba-201-ggwe-mukulu-wekka-song-lyrics" },
  { n: 202, slug: "oluyimba-202-mukama-twagala-song-lyrics" },
  { n: 203, slug: "oluyimba-203-endagaano-entukuvu-song-lyrics" },
  { n: 204, slug: "oluyimba-204-jjangu-kola-song-lyrics" },
  { n: 205, slug: "oluyimba-205-ayi-yesu-nkwegayiridde-song-lyrics" },
  { n: 206, slug: "oluyimba-206-ku-lwange-ne-ku-lwenjiri-song-lyrics" },
  { n: 207, slug: "oluyimba-207-mugende-mu-nsi-zonna-song-lyrics" },
  { n: 208, slug: "oluyimba-208-obwakabaka-bwo-song-lyrics" },
  { n: 209, slug: "oluyimba-209-obwakabaka-bwo-bujje-song-lyrics" },
  { n: 210, slug: "oluyimba-210-buli-muntu-yenna-awulire-song-lyrics" },
  { n: 211, slug: "oluyimba-211-katonda-waffewa-kisa-wa-maanyi-song-lyrics" },
  { n: 212, slug: "oluyimba-212-bulijjo-tumusuutenga-song-lyrics" },
  { n: 213, slug: "oluyimba-213-mmwe-ensozi-empanvu-ennyo-song-lyrics" },
  { n: 214, slug: "oluyimba-214-muwulire-mmwe-abantu-be-song-lyrics" },
  { n: 215, slug: "oluyimba-215-olwazi-kwe-yazimba-katonda-ekkanisa-song-lyrics" },
  { n: 216, slug: "oluyimba-216-lwananga-mu-lutalo-lwo-song-lyrics" },
  { n: 217, slug: "oluyimba-217-mmwe-bannange-abalwanyi-song-lyrics" },
  { n: 218, slug: "oluyimba-218-yesubwe-nnakusenga-song-lyrics" },
  { n: 219, slug: "oluyimba-219-yesu-ajja-abalabe-song-lyrics" },
  { n: 220, slug: "oluyimba-220-kale-ggye-lya-yesu-mugolokoke-song-lyrics" },
  { n: 221, slug: "oluyimba-221-balwanyi-ba-yesu-mwesibe-enkola-song-lyrics" },
  { n: 222, slug: "oluyimba-222-mulwanyi-wa-yesu-olina-ennaku-song-lyrics" },
  { n: 223, slug: "oluyimba-223-mmwe-mwenna-abooluganda-song-lyrics" },
  { n: 224, slug: "oluyimba-224-mwenna-muyimuke-song-lyrics" },
  { n: 225, slug: "oluyimba-225-ggwe-kibuga-kya-katonda-song-lyrics" },
  { n: 226, slug: "oluyimba-226-batuula-mu-ggulu-song-lyrics" },
  { n: 227, slug: "oluyimba-227-bulijjo-tutendereza-song-lyrics" },
  { n: 228, slug: "oluyimba-228-mu-nsi-yomu-ggulu-song-lyrics" },
  { n: 229, slug: "oluyimba-229-waliwo-ensi-esinga-eno-song-lyrics" },
  { n: 230, slug: "oluyimba-230-saayuuni-mu-ggulu-song-lyrics" },
  { n: 231, slug: "oluyimba-231-awamu-ne-yesuemirembe-gyonna-song-lyrics" },
  { n: 232, slug: "oluyimba-232-obulamu-bwaffe-buno-song-lyrics" },
  { n: 233, slug: "oluyimba-233-mu-kibuga-kya-katonda-song-lyrics" },
  { n: 234, slug: "oluyimba-234-bwe-tusiibula-abantu-song-lyrics" },
  { n: 235, slug: "oluyimba-235-wulira-eddoboozi-song-lyrics" },
  { n: 236, slug: "oluyimba-236-omuzibe-wamaaso-edda-song-lyrics" },
  { n: 237, slug: "oluyimba-237-laba-nnyimiridde-woli-song-lyrics" },
  { n: 238, slug: "oluyimba-238-jjangu-munnange-owulire-enjiri-song-lyrics" },
  { n: 239, slug: "oluyimba-239-mwoyo-gwange-wulira-song-lyrics" },
  { n: 240, slug: "oluyimba-240-wulira-mu-luyoogaano-song-lyrics" },
  { n: 241, slug: "oluyimba-241-yesu-abakkiriza-song-lyrics" },
  { n: 242, slug: "oluyimba-242-mujje-eri-yesu-temulwawo-song-lyrics" },
  { n: 243, slug: "oluyimba-243-mujje-mwenna-abakooye-song-lyrics" },
  { n: 244, slug: "oluyimba-244-ggwe-okooye-onafuwadde-song-lyrics" },
  { n: 245, slug: "oluyimba-245-mujje-mwennamujje-gye-ndi-song-lyrics" },
  { n: 246, slug: "oluyimba-246-mujje-mwenna-abakooye-song-lyrics" },
  { n: 247, slug: "oluyimba-247-ombuulire-ku-kisa-ekyomulokozi-song-lyrics" },
  { n: 248, slug: "oluyimba-248-enzikiza-yali-ebunye-ku-nsi-song-lyrics" },
  { n: 249, slug: "oluyimba-249-bwe-nnali-nga-neebakidde-ddala-song-lyrics" },
  { n: 250, slug: "oluyimba-250-tewali-mu-nsi-muno-mulongoofu-song-lyrics" },
  { n: 251, slug: "oluyimba-251-yimuka-ojje-eri-yesu-song-lyrics" },
  { n: 252, slug: "oluyimba-252-mmwe-mwenna-abanoonya-okutuuka-mu-ggulu-song-lyrics" },
  { n: 253, slug: "oluyimba-253-twagalane-okwagala-song-lyrics" },
  { n: 254, slug: "oluyimba-254-temusookanga-kunoonya-song-lyrics" },
  { n: 255, slug: "oluyimba-255-mu-nsi-yabagenyi-song-lyrics" },
  { n: 256, slug: "oluyimba-256-ayi-yesu-owekisa-song-lyrics" },
  { n: 257, slug: "oluyimba-257-nze-nkutunuulidde-song-lyrics" },
  { n: 258, slug: "oluyimba-258-ka-nkwagale-katondasiyinza-song-lyrics" },
  { n: 259, slug: "oluyimba-259-mu-biro-ebyennaku-song-lyrics" },
  { n: 260, slug: "oluyimba-260-kitaawe-wa-bonna-eri-ggwe-song-lyrics" },
  { n: 261, slug: "oluyimba-261-zuukuka-mwoyo-gwange-song-lyrics" },
  { n: 262, slug: "oluyimba-262-ensunu-nga-bweweevuuma-song-lyrics" },
  { n: 263, slug: "oluyimba-263-mukama-otuyigirize-song-lyrics" },
  { n: 264, slug: "oluyimba-264-ayi-yesu-mukama-song-lyrics" },
  { n: 265, slug: "oluyimba-265-yimirira-mu-ffe-song-lyrics" },
  { n: 266, slug: "oluyimba-266-yesu-bulijjo-nkwetaaga-song-lyrics" },
  { n: 267, slug: "oluyimba-267-katonda-onsembeze-song-lyrics" },
  { n: 268, slug: "oluyimba-268-yesu-eyasooka-song-lyrics" },
  { n: 269, slug: "oluyimba-269-omuyaga-gwali-guwuuma-song-lyrics" },
  { n: 270, slug: "oluyimba-270-yesu-kino-kye-njagala-song-lyrics" },
  { n: 271, slug: "oluyimba-271-katonda-eyantonda-nze-song-lyrics" },
  { n: 272, slug: "oluyimba-272-kitaffe-atwagala-fenna-song-lyrics" },
  { n: 273, slug: "oluyimba-273-mukama-waffe-owekisa-song-lyrics" },
  { n: 274, slug: "oluyimba-274-siyinzaayi-omulokozi-song-lyrics" },
  { n: 275, slug: "oluyimba-275-wulira-okusaba-kwange-song-lyrics" },
  { n: 276, slug: "oluyimba-276-ayi-kitaffe-owomu-ggulu-song-lyrics" },
  { n: 277, slug: "oluyimba-277-otukulemberemusumba-waffe-song-lyrics" },
  { n: 278, slug: "oluyimba-278-mukama-ggwe-omufuzi-wa-byonna-song-lyrics" },
  { n: 279, slug: "oluyimba-279-mukama-ggwe-ngabo-yaffe-song-lyrics" },
  { n: 280, slug: "oluyimba-280-ayi-katonda-waffe-song-lyrics" },
  { n: 281, slug: "oluyimba-281-yesuleero-nkukoowoola-song-lyrics" },
  { n: 282, slug: "oluyimba-282-yesu-njija-gyoli-song-lyrics" },
  { n: 283, slug: "oluyimba-283-onnumirize-olwebibi-song-lyrics" },
  { n: 284, slug: "oluyimba-284-siyinza-nakatono-song-lyrics" },
  { n: 285, slug: "oluyimba-285-ggwe-omanyi-yesu-obukoowu-bwaffe-song-lyrics" },
  { n: 286, slug: "oluyimba-286-ggwe-asuutibwa-buli-muntu-song-lyrics" },
  { n: 287, slug: "oluyimba-287-ekitiibwa-kyo-kinene-song-lyrics" },
  { n: 288, slug: "oluyimba-288-abaalumwa-emisota-abayisirayiri-song-lyrics" },
  { n: 289, slug: "oluyimba-289-yesu-yajja-alokole-song-lyrics" },
  { n: 290, slug: "oluyimba-290-yesu-amanyi-bwe-mbeera-song-lyrics" },
  { n: 291, slug: "oluyimba-291-mwenna-musanyuke-leero-song-lyrics" },
  { n: 292, slug: "oluyimba-292-katonda-tukutenda-ggwe-song-lyrics" },
  { n: 293, slug: "oluyimba-293-kaakano-twebaza-song-lyrics" },
  { n: 294, slug: "oluyimba-294-ekisa-kya-yesu-song-lyrics" },
  { n: 295, slug: "oluyimba-295-mukama-bwe-yamggamba-nti-song-lyrics" },
  { n: 296, slug: "oluyimba-296-ompisemukama-song-lyrics" },
  { n: 297, slug: "oluyimba-297-bye-tukuwa-biva-gyoli-song-lyrics" },
  { n: 298, slug: "oluyimba-298-mukamanze-nnina-ebibi-song-lyrics" },
  { n: 299, slug: "oluyimba-299-yesu-wanfiirira-mu-kwagala-kwo-song-lyrics" },
  { n: 300, slug: "oluyimba-300-omwoyo-nomubiri-song-lyrics" },
  { n: 301, slug: "oluyimba-301-katonda-wange-bye-nkyama-song-lyrics" },
  { n: 302, slug: "oluyimba-302-ekisa-kyo-tekitegeerekeka-song-lyrics" },
  { n: 303, slug: "oluyimba-303-siriiko-kye-mpozayesu-song-lyrics" },
  { n: 304, slug: "oluyimba-304-yesuneesiga-ggwe-okundokola-song-lyrics" },
  { n: 305, slug: "oluyimba-305-neewaayo-mu-mikono-song-lyrics" },
  { n: 306, slug: "oluyimba-306-otulumggamyemukama-waffe-song-lyrics" },
  { n: 307, slug: "oluyimba-307-yesusikyali-ku-bwange-song-lyrics" },
  { n: 308, slug: "oluyimba-308-ggwe-kwagala-kwa-katonda-song-lyrics" },
  { n: 309, slug: "oluyimba-309-twetaaga-yesu-yesuso-si-mulala-song-lyrics" },
  { n: 310, slug: "oluyimba-310-ayi-katondaonnumggamye-song-lyrics" },
  { n: 311, slug: "oluyimba-311-omwoyo-gwangewulira-amaloboozi-song-lyrics" },
  { n: 312, slug: "oluyimba-312-bwe-tutambulira-awamu-ne-yesu-song-lyrics" },
  { n: 313, slug: "oluyimba-313-ngempeewo-bwewejjawejja-song-lyrics" },
  { n: 314, slug: "oluyimba-314-mujje-mwekka-kyama-muwummule-song-lyrics" },
  { n: 315, slug: "oluyimba-315-kwata-omukono-gwangendi-munafu-song-lyrics" },
  { n: 316, slug: "oluyimba-316-otukulembere-song-lyrics" },
  { n: 317, slug: "oluyimba-317-abatambuzebayita-song-lyrics" },
  { n: 318, slug: "oluyimba-318-mmwe-mugenda-wa-bannange-song-lyrics" },
  { n: 319, slug: "oluyimba-319-mu-nzikiza-ggwe-omusana-ogwaka-song-lyrics" },
  { n: 320, slug: "oluyimba-320-kino-kye-nsiima-ennyo-song-lyrics" },
  { n: 321, slug: "oluyimba-321-bwe-ntambulira-mu-kkubo-song-lyrics" },
  { n: 322, slug: "oluyimba-322-yesu-omulokoziotuwulire-song-lyrics" },
  { n: 323, slug: "oluyimba-323-omutambuze-ngakooye-song-lyrics" },
  { n: 324, slug: "oluyimba-324-omuzira-yenna-song-lyrics" },
  { n: 325, slug: "oluyimba-325-bulijjobulijjo-song-lyrics" },
  { n: 326, slug: "oluyimba-326-abantu-ba-yesu-abalokole-song-lyrics" },
  { n: 327, slug: "oluyimba-327-yesu-mukama-wange-song-lyrics" },
  { n: 328, slug: "oluyimba-328-edda-nali-mbuusabuusa-song-lyrics" },
  { n: 329, slug: "oluyimba-329-gye-mirembe-nga-tuli-mu-bibi-song-lyrics" },
  { n: 330, slug: "oluyimba-330-yesu-mukama-wange-song-lyrics" },
  { n: 331, slug: "oluyimba-331-nkwesiga-yesu-mukama-song-lyrics" },
  { n: 332, slug: "oluyimba-332-nnina-omukwano-gwangeye-song-lyrics" },
  { n: 333, slug: "oluyimba-333-omukwano-gwa-yesu-song-lyrics" },
  { n: 334, slug: "oluyimba-334-nakola-nnyo-naye-saagasibwa-song-lyrics" },
  { n: 335, slug: "oluyimba-335-yesu-byonna-abimanyi-song-lyrics" },
  { n: 336, slug: "oluyimba-336-nga-beesiimye-abakwagala-song-lyrics" },
  { n: 337, slug: "oluyimba-337-yesu-mukama-omulokozi-song-lyrics" },
  { n: 338, slug: "oluyimba-338-nalyoka-ne-nkusenga-ggwe-song-lyrics" },
  { n: 339, slug: "oluyimba-339-katonda-musumba-wange-song-lyrics" },
  { n: 340, slug: "oluyimba-340-laba-omusumba-omulungi-song-lyrics" },
  { n: 341, slug: "oluyimba-341-jjo-ne-leero-nokutuusa-song-lyrics" },
  { n: 342, slug: "oluyimba-342-kikakafu-nnyoyesu-wange-song-lyrics" },
  { n: 343, slug: "oluyimba-343-nsanyukira-ekigambo-kino-song-lyrics" },
  { n: 344, slug: "oluyimba-344-abaana-abato-edda-song-lyrics" },
  { n: 345, slug: "oluyimba-345-ayi-mukama-waffe-song-lyrics" },
  { n: 346, slug: "oluyimba-346-awo-yesu-bwe-yatambula-song-lyrics" },
  { n: 347, slug: "oluyimba-347-ebinyu-ebirungi-ennyo-song-lyrics" },
  { n: 348, slug: "oluyimba-348-ekiro-nga-neebase-song-lyrics" },
  { n: 349, slug: "oluyimba-349-ggwe-musumba-omulungi-song-lyrics" },
  { n: 350, slug: "oluyimba-350-katonda-tusiibule-nno-song-lyrics" },
  { n: 351, slug: "oluyimba-351-katonda-wanjagala-song-lyrics" },
  { n: 352, slug: "oluyimba-352-kigambo-kya-magero-nnyo-song-lyrics" },
  { n: 353, slug: "oluyimba-353-mukama-wange-nkwebaza-song-lyrics" },
  { n: 354, slug: "oluyimba-354-omutambuze-nze-song-lyrics" },
  { n: 355, slug: "oluyimba-355-omutambuze-omuto-nze-song-lyrics" },
  { n: 356, slug: "oluyimba-356-temuyonoonanga-song-lyrics" },
  { n: 357, slug: "oluyimba-357-tuleeta-ebirabo-song-lyrics" },
  { n: 358, slug: "oluyimba-358-tulina-kabaka-waffe-song-lyrics" },
  { n: 359, slug: "oluyimba-359-wulira-okusaba-kwange-song-lyrics" },
  { n: 360, slug: "oluyimba-360-yesumukama-wange-song-lyrics" },
  { n: 361, slug: "oluyimba-361-yesu-musumba-wange-song-lyrics" },
  { n: 362, slug: "oluyimba-362-yesu-ye-anjagala-song-lyrics" },
  { n: 363, slug: "oluyimba-363-katonda-mu-ggulu-song-lyrics" },
  { n: 364, slug: "oluyimba-364-edda-bonna-abalwadde-song-lyrics" },
  { n: 365, slug: "oluyimba-365-edda-mu-nsi-abayudaaya-song-lyrics" },
  { n: 366, slug: "oluyimba-366-obudde-bwe-bwawungeera-song-lyrics" },
  { n: 367, slug: "oluyimba-367-omulokozi-waffe-song-lyrics" },
  { n: 368, slug: "oluyimba-368-amaze-omulimu-gwe-song-lyrics" },
  { n: 369, slug: "oluyimba-369-baweereddwa-abafu-song-lyrics" },
  { n: 370, slug: "oluyimba-370-mu-buyinike-obungi-song-lyrics" },
  { n: 371, slug: "oluyimba-371-kabaka-weggulu-nensi-song-lyrics" },
  { n: 372, slug: "oluyimba-372-katonda-tumwebaze-song-lyrics" },
  { n: 373, slug: "oluyimba-373-omwana-wo-nkukoowoola-song-lyrics" },
  { n: 374, slug: "oluyimba-374-tutende-nnyo-mukama-song-lyrics" },
  { n: 375, slug: "oluyimba-375-tusiga-ensigo-ennungi-song-lyrics" },
  { n: 376, slug: "oluyimba-376-katonda-lwe-lwazi-lwaffe-song-lyrics" },
  { n: 377, slug: "oluyimba-377-katonda-owokwagala-song-lyrics" },
  { n: 378, slug: "oluyimba-378-mukama-tufukamidde-song-lyrics" },
  { n: 379, slug: "oluyimba-379-katonda-abeerenga-naawe-song-lyrics" },
  { n: 380, slug: "oluyimba-380-bewaayo-abaana-beebazibwa-song-lyrics" },
  { n: 381, slug: "oluyimba-381-ayi-katonda-ogikuume-song-lyrics" },
  { n: 382, slug: "oluyimba-382-obudde-buzibyeyesu-song-lyrics" },
  { n: 383, slug: "oluyimba-383-waaliwo-edda-omuwalayalagulwa-bannabbi-song-lyrics" },
  { n: 384, slug: "oluyimba-384-sikukulu-eyasoka-yajira-abasumba-abalunda-song-lyrics" },
  { n: 385, slug: "oluyimba-385-ojeomwoyoomutukuvu-omulise-emitima-gyaffe-song-lyrics" },
  { n: 386, slug: "oluyimba-386-omutukuvu-omutukuvu-song-lyrics" },
  { n: 387, slug: "oluyimba-387-omwana-gwendiga-song-lyrics" },
  { n: 388, slug: "oluyimba-388-ensi-zonna-ziyimbe-song-lyrics" },
  { n: 389, slug: "oluyimba-389-katonda-byasima-ye-birikolerwa-dala-song-lyrics" },
  { n: 390, slug: "oluyimba-390-ai-mukama-musumbaotuwe-olwekisakyo-song-lyrics" },
  { n: 391, slug: "oluyimba-391-obudde-nga-buyita-song-lyrics" },
  { n: 392, slug: "oluyimba-392-simanyi-binabaawo-song-lyrics" },
  { n: 393, slug: "oluyimba-393-mu-myaka-si-mingi-song-lyrics" },
  { n: 394, slug: "oluyimba-394-abalaguzi-eda-bava-wala-nnyo-song-lyrics" },
  { n: 395, slug: "oluyimba-395-beraai-yesumukutegera-kwange-song-lyrics" },
  { n: 396, slug: "oluyimba-396-beramukamamunda-yange-song-lyrics" },
  { n: 397, slug: "oluyimba-397-leero-ka-nneesibirire-song-lyrics" },
  { n: 398, slug: "oluyimba-398-mu-nzikiza-ekutte-nkukaabidde-song-lyrics" },
  { n: 399, slug: "oluyimba-399-mmwe-abantu-mu-mumuwulire-song-lyrics" },
  { n: 400, slug: "oluyimba-400-amina-amina-song-lyrics" },
  { n: 401, slug: "oluyimba-401-tutendereza-lero-song-lyrics" },
  { n: 402, slug: "oluyimba-402-munnaffe-oyo-awumudde-song-lyrics" },
  { n: 403, slug: "oluyimba-403-ekiro-ekyoekyettendo-song-lyrics" },
  { n: 404, slug: "oluyimba-404-tulindirire-okujja-kwa-yesu-song-lyrics" },
  { n: 405, slug: "oluyimba-405-ekisa-kya-yesu-song-lyrics" },
  { n: 406, slug: "oluyimba-406-waaliwo-edda-omuwala-song-lyrics" },
  { n: 407, slug: "oluyimba-407-ndidayo-mu-gulu-song-lyrics" },
  { n: 408, slug: "oluyimba-408-mujje-ku-mbaga-song-lyrics" },
  { n: 409, slug: "oluyimba-409-amaka-amatukuvu-song-lyrics" },
  { n: 410, slug: "oluyimba-410-bwetulisimbibwa-awali-yesu-song-lyrics" },
  { n: 411, slug: "oluyimba-411-katonda-yakuuma-abaanabe-song-lyrics" },
  { n: 412, slug: "oluyimba-412-yimba-ggwe-mwoyo-gwange-song-lyrics" }
];

async function scrapeHymns() {
  const fullHymns = [];
  const totalHymns = HYMN_SLUGS.length;

  for (const item of HYMN_SLUGS) {
    const url = `${BASE}/${item.slug}`;
    try {
      console.log(`Scraping [${item.n}/${totalHymns}]: ${item.slug}...`);
      const { data } = await axios.get(url, {
        headers: { 'User-Agent': 'Mozilla/5.0' }
      });
      const $ = cheerio.load(data);

      // Extract the title from the main heading
      const title = $('h1').text().trim() || `Oluyimba ${item.n}`;
      
      // Extract lyrics safely using paragraph tags or body fallback
      let lyrics = '';
      const paragraphs = $('p');

      if (paragraphs.length > 0) {
        paragraphs.each((i, el) => {
          lyrics += $(el).text().trim() + '\n\n';
        });
      } else {
        lyrics = $('body').text().trim();
      }

      fullHymns.push({
        n: item.n,
        slug: item.slug,
        title: title,
        lyrics: lyrics.trim() || "Lyrics loading soon..."
      });

      // Polite 300ms delay between requests to avoid rate limits
      await new Promise((resolve) => setTimeout(resolve, 300));
    } catch (error) {
      console.error(`Failed hymn ${item.n}:`, error.message);
      fullHymns.push({
        n: item.n,
        slug: item.slug,
        title: `Oluyimba ${item.n}`,
        lyrics: "Could not load lyrics."
      });
    }
  }
  // Create assets folder if it doesn't exist
  if (!fs.existsSync('assets')) {
    fs.mkdirSync('assets');
  }

  // Save directly into the assets folder
  fs.writeFileSync('assets/hymns-full.json', JSON.stringify(fullHymns, null, 2), 'utf-8');
  console.log("Finished! Saved hymns-full.json inside assets/ folder successfully.");
}

scrapeHymns();