name: Flutter web

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.7"
          cache: true
      - run: flutter pub get
      - run: flutter build web --release
